spring:
  application:
    name: User-Service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: 972114@Ss
    #password: root9721

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
      fetch-registry: true
      registry-with-eureka: true
  instance:
  prefer-ip-address: true