spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: onedayworker
    password: onedayworker

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/customer_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: true