spring:
  application:
    name: Customer-Service
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.boot.context.config: DEBUG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true


